/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryPreferenceRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.CategoryPreferenceRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Integer, java.lang.Double> {

	private static final long serialVersionUID = -1298409184;

	/**
	 * Setter for <code>incomb.category_preference.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.category_preference.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.category_preference.category_id</code>.
	 */
	public void setCategoryId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.category_preference.category_id</code>.
	 */
	public java.lang.Integer getCategoryId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>incomb.category_preference.factor</code>.
	 */
	public void setFactor(java.lang.Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.category_preference.factor</code>.
	 */
	public java.lang.Double getFactor() {
		return (java.lang.Double) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Integer, java.lang.Double> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Integer, java.lang.Double> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE.CATEGORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field3() {
		return com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE.FACTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getCategoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value3() {
		return getFactor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPreferenceRecord value1(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPreferenceRecord value2(java.lang.Integer value) {
		setCategoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPreferenceRecord value3(java.lang.Double value) {
		setFactor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPreferenceRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Double value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CategoryPreferenceRecord
	 */
	public CategoryPreferenceRecord() {
		super(com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE);
	}

	/**
	 * Create a detached, initialised CategoryPreferenceRecord
	 */
	public CategoryPreferenceRecord(java.lang.Long userId, java.lang.Integer categoryId, java.lang.Double factor) {
		super(com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE);

		setValue(0, userId);
		setValue(1, categoryId);
		setValue(2, factor);
	}
}
