/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.CategoryRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 874134152;

	/**
	 * Setter for <code>incomb.category.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.category.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>incomb.category.name_key</code>.
	 */
	public void setNameKey(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.category.name_key</code>.
	 */
	public java.lang.String getNameKey() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>incomb.category.image_path</code>.
	 */
	public void setImagePath(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.category.image_path</code>.
	 */
	public java.lang.String getImagePath() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>incomb.category.module_id</code>.
	 */
	public void setModuleId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>incomb.category.module_id</code>.
	 */
	public java.lang.Integer getModuleId() {
		return (java.lang.Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.incomb.server.model.tables.CategoryTable.CATEGORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.incomb.server.model.tables.CategoryTable.CATEGORY.NAME_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.incomb.server.model.tables.CategoryTable.CATEGORY.IMAGE_PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.incomb.server.model.tables.CategoryTable.CATEGORY.MODULE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNameKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getImagePath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getModuleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryRecord value2(java.lang.String value) {
		setNameKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryRecord value3(java.lang.String value) {
		setImagePath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryRecord value4(java.lang.Integer value) {
		setModuleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CategoryRecord
	 */
	public CategoryRecord() {
		super(com.incomb.server.model.tables.CategoryTable.CATEGORY);
	}

	/**
	 * Create a detached, initialised CategoryRecord
	 */
	public CategoryRecord(java.lang.Integer id, java.lang.String nameKey, java.lang.String imagePath, java.lang.Integer moduleId) {
		super(com.incomb.server.model.tables.CategoryTable.CATEGORY);

		setValue(0, id);
		setValue(1, nameKey);
		setValue(2, imagePath);
		setValue(3, moduleId);
	}
}
