/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CombItemRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.CombItemRecord> implements org.jooq.Record4<java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1417567010;

	/**
	 * Setter for <code>incomb.comb_Item.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.comb_Item.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.comb_Item.content_id</code>.
	 */
	public void setContentId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.comb_Item.content_id</code>.
	 */
	public java.lang.Long getContentId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>incomb.comb_Item.add_date</code>.
	 */
	public void setAddDate(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.comb_Item.add_date</code>.
	 */
	public java.sql.Timestamp getAddDate() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>incomb.comb_Item.read_date</code>.
	 */
	public void setReadDate(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>incomb.comb_Item.read_date</code>.
	 */
	public java.sql.Timestamp getReadDate() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.CombItemTable.COMB_ITEM.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.incomb.server.model.tables.CombItemTable.COMB_ITEM.CONTENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return com.incomb.server.model.tables.CombItemTable.COMB_ITEM.ADD_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.incomb.server.model.tables.CombItemTable.COMB_ITEM.READ_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getContentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getAddDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getReadDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CombItemRecord value1(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CombItemRecord value2(java.lang.Long value) {
		setContentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CombItemRecord value3(java.sql.Timestamp value) {
		setAddDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CombItemRecord value4(java.sql.Timestamp value) {
		setReadDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CombItemRecord values(java.lang.Long value1, java.lang.Long value2, java.sql.Timestamp value3, java.sql.Timestamp value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CombItemRecord
	 */
	public CombItemRecord() {
		super(com.incomb.server.model.tables.CombItemTable.COMB_ITEM);
	}

	/**
	 * Create a detached, initialised CombItemRecord
	 */
	public CombItemRecord(java.lang.Long userId, java.lang.Long contentId, java.sql.Timestamp addDate, java.sql.Timestamp readDate) {
		super(com.incomb.server.model.tables.CombItemTable.COMB_ITEM);

		setValue(0, userId);
		setValue(1, contentId);
		setValue(2, addDate);
		setValue(3, readDate);
	}
}
