/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.ContentRecord> implements org.jooq.Record8<java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Boolean> {

	private static final long serialVersionUID = 1166838679;

	/**
	 * Setter for <code>incomb.content.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.content.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.content.provider_id</code>.
	 */
	public void setProviderId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.content.provider_id</code>.
	 */
	public java.lang.Integer getProviderId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>incomb.content.category_id</code>.
	 */
	public void setCategoryId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.content.category_id</code>.
	 */
	public java.lang.Integer getCategoryId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>incomb.content.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>incomb.content.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>incomb.content.locale</code>.
	 */
	public void setLocale(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>incomb.content.locale</code>.
	 */
	public java.lang.String getLocale() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>incomb.content.text</code>.
	 */
	public void setText(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>incomb.content.text</code>.
	 */
	public java.lang.String getText() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>incomb.content.publish_date</code>.
	 */
	public void setPublishDate(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>incomb.content.publish_date</code>.
	 */
	public java.sql.Timestamp getPublishDate() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>incomb.content.indexed</code>.
	 */
	public void setIndexed(java.lang.Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>incomb.content.indexed</code>.
	 */
	public java.lang.Boolean getIndexed() {
		return (java.lang.Boolean) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.ContentTable.CONTENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.incomb.server.model.tables.ContentTable.CONTENT.PROVIDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.incomb.server.model.tables.ContentTable.CONTENT.CATEGORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.incomb.server.model.tables.ContentTable.CONTENT.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.incomb.server.model.tables.ContentTable.CONTENT.LOCALE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.incomb.server.model.tables.ContentTable.CONTENT.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return com.incomb.server.model.tables.ContentTable.CONTENT.PUBLISH_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return com.incomb.server.model.tables.ContentTable.CONTENT.INDEXED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getProviderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getCategoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getLocale();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getPublishDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getIndexed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentRecord value2(java.lang.Integer value) {
		setProviderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentRecord value3(java.lang.Integer value) {
		setCategoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentRecord value4(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentRecord value5(java.lang.String value) {
		setLocale(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentRecord value6(java.lang.String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentRecord value7(java.sql.Timestamp value) {
		setPublishDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentRecord value8(java.lang.Boolean value) {
		setIndexed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.sql.Timestamp value7, java.lang.Boolean value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContentRecord
	 */
	public ContentRecord() {
		super(com.incomb.server.model.tables.ContentTable.CONTENT);
	}

	/**
	 * Create a detached, initialised ContentRecord
	 */
	public ContentRecord(java.lang.Long id, java.lang.Integer providerId, java.lang.Integer categoryId, java.lang.String title, java.lang.String locale, java.lang.String text, java.sql.Timestamp publishDate, java.lang.Boolean indexed) {
		super(com.incomb.server.model.tables.ContentTable.CONTENT);

		setValue(0, id);
		setValue(1, providerId);
		setValue(2, categoryId);
		setValue(3, title);
		setValue(4, locale);
		setValue(5, text);
		setValue(6, publishDate);
		setValue(7, indexed);
	}
}
