/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentSourceRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.ContentSourceRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1857665630;

	/**
	 * Setter for <code>incomb.content_source.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.content_source.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>incomb.content_source.provider_id</code>.
	 */
	public void setProviderId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.content_source.provider_id</code>.
	 */
	public java.lang.Integer getProviderId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>incomb.content_source.category_id</code>.
	 */
	public void setCategoryId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.content_source.category_id</code>.
	 */
	public java.lang.Integer getCategoryId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>incomb.content_source.interval</code>.
	 */
	public void setInterval(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>incomb.content_source.interval</code>.
	 */
	public java.lang.Integer getInterval() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>incomb.content_source.url</code>.
	 */
	public void setUrl(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>incomb.content_source.url</code>.
	 */
	public java.lang.String getUrl() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>incomb.content_source.locale</code>.
	 */
	public void setLocale(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>incomb.content_source.locale</code>.
	 */
	public java.lang.String getLocale() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.PROVIDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.CATEGORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.INTERVAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.LOCALE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getProviderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getCategoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getInterval();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getLocale();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentSourceRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentSourceRecord value2(java.lang.Integer value) {
		setProviderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentSourceRecord value3(java.lang.Integer value) {
		setCategoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentSourceRecord value4(java.lang.Integer value) {
		setInterval(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentSourceRecord value5(java.lang.String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentSourceRecord value6(java.lang.String value) {
		setLocale(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentSourceRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.String value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContentSourceRecord
	 */
	public ContentSourceRecord() {
		super(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE);
	}

	/**
	 * Create a detached, initialised ContentSourceRecord
	 */
	public ContentSourceRecord(java.lang.Integer id, java.lang.Integer providerId, java.lang.Integer categoryId, java.lang.Integer interval, java.lang.String url, java.lang.String locale) {
		super(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE);

		setValue(0, id);
		setValue(1, providerId);
		setValue(2, categoryId);
		setValue(3, interval);
		setValue(4, url);
		setValue(5, locale);
	}
}
