/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentCommentRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.ContentCommentRecord> implements org.jooq.Record5<java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = -2009412363;

	/**
	 * Setter for <code>incomb.content_comment.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.content_comment.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.content_comment.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.content_comment.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>incomb.content_comment.content_id</code>.
	 */
	public void setContentId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.content_comment.content_id</code>.
	 */
	public java.lang.Long getContentId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>incomb.content_comment.comment_date</code>.
	 */
	public void setCommentDate(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>incomb.content_comment.comment_date</code>.
	 */
	public java.sql.Timestamp getCommentDate() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>incomb.content_comment.comment</code>.
	 */
	public void setComment(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>incomb.content_comment.comment</code>.
	 */
	public java.lang.String getComment() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT.CONTENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT.COMMENT_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT.COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getContentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getCommentDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getComment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentCommentRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentCommentRecord value2(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentCommentRecord value3(java.lang.Long value) {
		setContentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentCommentRecord value4(java.sql.Timestamp value) {
		setCommentDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentCommentRecord value5(java.lang.String value) {
		setComment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentCommentRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3, java.sql.Timestamp value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContentCommentRecord
	 */
	public ContentCommentRecord() {
		super(com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT);
	}

	/**
	 * Create a detached, initialised ContentCommentRecord
	 */
	public ContentCommentRecord(java.lang.Long id, java.lang.Long userId, java.lang.Long contentId, java.sql.Timestamp commentDate, java.lang.String comment) {
		super(com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT);

		setValue(0, id);
		setValue(1, userId);
		setValue(2, contentId);
		setValue(3, commentDate);
		setValue(4, comment);
	}
}
