/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentVoteRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.ContentVoteRecord> implements org.jooq.Record4<java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.Boolean> {

	private static final long serialVersionUID = 367794270;

	/**
	 * Setter for <code>incomb.content_vote.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.content_vote.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.content_vote.content_id</code>.
	 */
	public void setContentId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.content_vote.content_id</code>.
	 */
	public java.lang.Long getContentId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>incomb.content_vote.vote_date</code>.
	 */
	public void setVoteDate(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.content_vote.vote_date</code>.
	 */
	public java.sql.Timestamp getVoteDate() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>incomb.content_vote.up</code>.
	 */
	public void setUp(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>incomb.content_vote.up</code>.
	 */
	public java.lang.Boolean getUp() {
		return (java.lang.Boolean) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.CONTENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.VOTE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.UP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getContentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getVoteDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getUp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentVoteRecord value1(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentVoteRecord value2(java.lang.Long value) {
		setContentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentVoteRecord value3(java.sql.Timestamp value) {
		setVoteDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentVoteRecord value4(java.lang.Boolean value) {
		setUp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContentVoteRecord values(java.lang.Long value1, java.lang.Long value2, java.sql.Timestamp value3, java.lang.Boolean value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContentVoteRecord
	 */
	public ContentVoteRecord() {
		super(com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE);
	}

	/**
	 * Create a detached, initialised ContentVoteRecord
	 */
	public ContentVoteRecord(java.lang.Long userId, java.lang.Long contentId, java.sql.Timestamp voteDate, java.lang.Boolean up) {
		super(com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE);

		setValue(0, userId);
		setValue(1, contentId);
		setValue(2, voteDate);
		setValue(3, up);
	}
}
