/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlyWithRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.FlyWithRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.sql.Timestamp> {

	private static final long serialVersionUID = 789905596;

	/**
	 * Setter for <code>incomb.fly_with.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.fly_with.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.fly_with.fly_with_id</code>.
	 */
	public void setFlyWithId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.fly_with.fly_with_id</code>.
	 */
	public java.lang.Long getFlyWithId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>incomb.fly_with.fly_with_start_date</code>.
	 */
	public void setFlyWithStartDate(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.fly_with.fly_with_start_date</code>.
	 */
	public java.sql.Timestamp getFlyWithStartDate() {
		return (java.sql.Timestamp) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.FlyWithTable.FLY_WITH.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.incomb.server.model.tables.FlyWithTable.FLY_WITH.FLY_WITH_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return com.incomb.server.model.tables.FlyWithTable.FLY_WITH.FLY_WITH_START_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getFlyWithId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getFlyWithStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlyWithRecord value1(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlyWithRecord value2(java.lang.Long value) {
		setFlyWithId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlyWithRecord value3(java.sql.Timestamp value) {
		setFlyWithStartDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlyWithRecord values(java.lang.Long value1, java.lang.Long value2, java.sql.Timestamp value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FlyWithRecord
	 */
	public FlyWithRecord() {
		super(com.incomb.server.model.tables.FlyWithTable.FLY_WITH);
	}

	/**
	 * Create a detached, initialised FlyWithRecord
	 */
	public FlyWithRecord(java.lang.Long userId, java.lang.Long flyWithId, java.sql.Timestamp flyWithStartDate) {
		super(com.incomb.server.model.tables.FlyWithTable.FLY_WITH);

		setValue(0, userId);
		setValue(1, flyWithId);
		setValue(2, flyWithStartDate);
	}
}
