/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.ModuleRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 350449827;

	/**
	 * Setter for <code>incomb.module.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.module.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>incomb.module.name_key</code>.
	 */
	public void setNameKey(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.module.name_key</code>.
	 */
	public java.lang.String getNameKey() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>incomb.module.image_path</code>.
	 */
	public void setImagePath(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.module.image_path</code>.
	 */
	public java.lang.String getImagePath() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>incomb.module.template_path</code>.
	 */
	public void setTemplatePath(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>incomb.module.template_path</code>.
	 */
	public java.lang.String getTemplatePath() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.incomb.server.model.tables.ModuleTable.MODULE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.incomb.server.model.tables.ModuleTable.MODULE.NAME_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.incomb.server.model.tables.ModuleTable.MODULE.IMAGE_PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.incomb.server.model.tables.ModuleTable.MODULE.TEMPLATE_PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNameKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getImagePath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTemplatePath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModuleRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModuleRecord value2(java.lang.String value) {
		setNameKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModuleRecord value3(java.lang.String value) {
		setImagePath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModuleRecord value4(java.lang.String value) {
		setTemplatePath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModuleRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ModuleRecord
	 */
	public ModuleRecord() {
		super(com.incomb.server.model.tables.ModuleTable.MODULE);
	}

	/**
	 * Create a detached, initialised ModuleRecord
	 */
	public ModuleRecord(java.lang.Integer id, java.lang.String nameKey, java.lang.String imagePath, java.lang.String templatePath) {
		super(com.incomb.server.model.tables.ModuleTable.MODULE);

		setValue(0, id);
		setValue(1, nameKey);
		setValue(2, imagePath);
		setValue(3, templatePath);
	}
}
