/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.NewsRecord> implements org.jooq.Record6<java.lang.Long, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Long> {

	private static final long serialVersionUID = -1305236825;

	/**
	 * Setter for <code>incomb.news.content_id</code>.
	 */
	public void setContentId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.news.content_id</code>.
	 */
	public java.lang.Long getContentId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.news.link</code>.
	 */
	public void setLink(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.news.link</code>.
	 */
	public java.lang.String getLink() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>incomb.news.image_url</code>.
	 */
	public void setImageUrl(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.news.image_url</code>.
	 */
	public java.lang.String getImageUrl() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>incomb.news.image_width</code>.
	 */
	public void setImageWidth(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>incomb.news.image_width</code>.
	 */
	public java.lang.Integer getImageWidth() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>incomb.news.image_height</code>.
	 */
	public void setImageHeight(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>incomb.news.image_height</code>.
	 */
	public java.lang.Integer getImageHeight() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>incomb.news.news_group_id</code>.
	 */
	public void setNewsGroupId(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>incomb.news.news_group_id</code>.
	 */
	public java.lang.Long getNewsGroupId() {
		return (java.lang.Long) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Long> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Long> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.NewsTable.NEWS.CONTENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.incomb.server.model.tables.NewsTable.NEWS.LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.incomb.server.model.tables.NewsTable.NEWS.IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.incomb.server.model.tables.NewsTable.NEWS.IMAGE_WIDTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.incomb.server.model.tables.NewsTable.NEWS.IMAGE_HEIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return com.incomb.server.model.tables.NewsTable.NEWS.NEWS_GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getContentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getImageWidth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getImageHeight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getNewsGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NewsRecord value1(java.lang.Long value) {
		setContentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NewsRecord value2(java.lang.String value) {
		setLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NewsRecord value3(java.lang.String value) {
		setImageUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NewsRecord value4(java.lang.Integer value) {
		setImageWidth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NewsRecord value5(java.lang.Integer value) {
		setImageHeight(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NewsRecord value6(java.lang.Long value) {
		setNewsGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NewsRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Long value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NewsRecord
	 */
	public NewsRecord() {
		super(com.incomb.server.model.tables.NewsTable.NEWS);
	}

	/**
	 * Create a detached, initialised NewsRecord
	 */
	public NewsRecord(java.lang.Long contentId, java.lang.String link, java.lang.String imageUrl, java.lang.Integer imageWidth, java.lang.Integer imageHeight, java.lang.Long newsGroupId) {
		super(com.incomb.server.model.tables.NewsTable.NEWS);

		setValue(0, contentId);
		setValue(1, link);
		setValue(2, imageUrl);
		setValue(3, imageWidth);
		setValue(4, imageHeight);
		setValue(5, newsGroupId);
	}
}
