/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.PermissionRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1600956164;

	/**
	 * Setter for <code>incomb.permission.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.permission.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>incomb.permission.name_key</code>.
	 */
	public void setNameKey(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.permission.name_key</code>.
	 */
	public java.lang.String getNameKey() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.incomb.server.model.tables.PermissionTable.PERMISSION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.incomb.server.model.tables.PermissionTable.PERMISSION.NAME_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNameKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value2(java.lang.String value) {
		setNameKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord values(java.lang.Integer value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PermissionRecord
	 */
	public PermissionRecord() {
		super(com.incomb.server.model.tables.PermissionTable.PERMISSION);
	}

	/**
	 * Create a detached, initialised PermissionRecord
	 */
	public PermissionRecord(java.lang.Integer id, java.lang.String nameKey) {
		super(com.incomb.server.model.tables.PermissionTable.PERMISSION);

		setValue(0, id);
		setValue(1, nameKey);
	}
}
