/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProviderRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.ProviderRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -705955491;

	/**
	 * Setter for <code>incomb.provider.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.provider.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>incomb.provider.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.provider.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>incomb.provider.image_path</code>.
	 */
	public void setImagePath(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.provider.image_path</code>.
	 */
	public java.lang.String getImagePath() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>incomb.provider.website</code>.
	 */
	public void setWebsite(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>incomb.provider.website</code>.
	 */
	public java.lang.String getWebsite() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>incomb.provider.parser_class</code>.
	 */
	public void setParserClass(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>incomb.provider.parser_class</code>.
	 */
	public java.lang.String getParserClass() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.incomb.server.model.tables.ProviderTable.PROVIDER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.incomb.server.model.tables.ProviderTable.PROVIDER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.incomb.server.model.tables.ProviderTable.PROVIDER.IMAGE_PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.incomb.server.model.tables.ProviderTable.PROVIDER.WEBSITE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.incomb.server.model.tables.ProviderTable.PROVIDER.PARSER_CLASS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getImagePath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getWebsite();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getParserClass();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProviderRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProviderRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProviderRecord value3(java.lang.String value) {
		setImagePath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProviderRecord value4(java.lang.String value) {
		setWebsite(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProviderRecord value5(java.lang.String value) {
		setParserClass(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProviderRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProviderRecord
	 */
	public ProviderRecord() {
		super(com.incomb.server.model.tables.ProviderTable.PROVIDER);
	}

	/**
	 * Create a detached, initialised ProviderRecord
	 */
	public ProviderRecord(java.lang.Integer id, java.lang.String name, java.lang.String imagePath, java.lang.String website, java.lang.String parserClass) {
		super(com.incomb.server.model.tables.ProviderTable.PROVIDER);

		setValue(0, id);
		setValue(1, name);
		setValue(2, imagePath);
		setValue(3, website);
		setValue(4, parserClass);
	}
}
