/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProviderExclusionRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.ProviderExclusionRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 521414347;

	/**
	 * Setter for <code>incomb.provider_exclusion.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.provider_exclusion.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.provider_exclusion.provider_id</code>.
	 */
	public void setProviderId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.provider_exclusion.provider_id</code>.
	 */
	public java.lang.Integer getProviderId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>incomb.provider_exclusion.category_id</code>.
	 */
	public void setCategoryId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.provider_exclusion.category_id</code>.
	 */
	public java.lang.Integer getCategoryId() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.lang.Long, java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION.PROVIDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION.CATEGORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getProviderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getCategoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProviderExclusionRecord value1(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProviderExclusionRecord value2(java.lang.Integer value) {
		setProviderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProviderExclusionRecord value3(java.lang.Integer value) {
		setCategoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProviderExclusionRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProviderExclusionRecord
	 */
	public ProviderExclusionRecord() {
		super(com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION);
	}

	/**
	 * Create a detached, initialised ProviderExclusionRecord
	 */
	public ProviderExclusionRecord(java.lang.Long userId, java.lang.Integer providerId, java.lang.Integer categoryId) {
		super(com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION);

		setValue(0, userId);
		setValue(1, providerId);
		setValue(2, categoryId);
	}
}
