/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleNmPermissionRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.RoleNmPermissionRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1180889673;

	/**
	 * Setter for <code>incomb.role_nm_permission.role_id</code>.
	 */
	public void setRoleId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.role_nm_permission.role_id</code>.
	 */
	public java.lang.Integer getRoleId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>incomb.role_nm_permission.permission_id</code>.
	 */
	public void setPermissionId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.role_nm_permission.permission_id</code>.
	 */
	public java.lang.Integer getPermissionId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION.ROLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION.PERMISSION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getRoleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getPermissionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoleNmPermissionRecord value1(java.lang.Integer value) {
		setRoleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoleNmPermissionRecord value2(java.lang.Integer value) {
		setPermissionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoleNmPermissionRecord values(java.lang.Integer value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RoleNmPermissionRecord
	 */
	public RoleNmPermissionRecord() {
		super(com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION);
	}

	/**
	 * Create a detached, initialised RoleNmPermissionRecord
	 */
	public RoleNmPermissionRecord(java.lang.Integer roleId, java.lang.Integer permissionId) {
		super(com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION);

		setValue(0, roleId);
		setValue(1, permissionId);
	}
}
