/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RssFeedContentSourceRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.RssFeedContentSourceRecord> implements org.jooq.Record1<java.lang.Integer> {

	private static final long serialVersionUID = 1231977687;

	/**
	 * Setter for <code>incomb.rss_feed_content_source.content_source_id</code>.
	 */
	public void setContentSourceId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.rss_feed_content_source.content_source_id</code>.
	 */
	public java.lang.Integer getContentSourceId() {
		return (java.lang.Integer) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.Integer> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.Integer> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE.CONTENT_SOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getContentSourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RssFeedContentSourceRecord value1(java.lang.Integer value) {
		setContentSourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RssFeedContentSourceRecord values(java.lang.Integer value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RssFeedContentSourceRecord
	 */
	public RssFeedContentSourceRecord() {
		super(com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE);
	}

	/**
	 * Create a detached, initialised RssFeedContentSourceRecord
	 */
	public RssFeedContentSourceRecord(java.lang.Integer contentSourceId) {
		super(com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE);

		setValue(0, contentSourceId);
	}
}
