/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLocaleRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.UserLocaleRecord> implements org.jooq.Record2<java.lang.Long, java.lang.String> {

	private static final long serialVersionUID = -742887400;

	/**
	 * Setter for <code>incomb.user_locale.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.user_locale.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.user_locale.locale</code>.
	 */
	public void setLocale(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.user_locale.locale</code>.
	 */
	public java.lang.String getLocale() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE.LOCALE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLocale();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserLocaleRecord value1(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserLocaleRecord value2(java.lang.String value) {
		setLocale(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserLocaleRecord values(java.lang.Long value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserLocaleRecord
	 */
	public UserLocaleRecord() {
		super(com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE);
	}

	/**
	 * Create a detached, initialised UserLocaleRecord
	 */
	public UserLocaleRecord(java.lang.Long userId, java.lang.String locale) {
		super(com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE);

		setValue(0, userId);
		setValue(1, locale);
	}
}
