/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNmRoleRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.UserNmRoleRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Integer> {

	private static final long serialVersionUID = 1418643801;

	/**
	 * Setter for <code>incomb.user_nm_role.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.user_nm_role.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.user_nm_role.role_id</code>.
	 */
	public void setRoleId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.user_nm_role.role_id</code>.
	 */
	public java.lang.Integer getRoleId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE.ROLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRoleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNmRoleRecord value1(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNmRoleRecord value2(java.lang.Integer value) {
		setRoleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNmRoleRecord values(java.lang.Long value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserNmRoleRecord
	 */
	public UserNmRoleRecord() {
		super(com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE);
	}

	/**
	 * Create a detached, initialised UserNmRoleRecord
	 */
	public UserNmRoleRecord(java.lang.Long userId, java.lang.Integer roleId) {
		super(com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE);

		setValue(0, userId);
		setValue(1, roleId);
	}
}
