/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends org.jooq.impl.UpdatableRecordImpl<com.incomb.server.model.records.UserRecord> implements org.jooq.Record9<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Boolean, java.lang.Boolean> {

	private static final long serialVersionUID = 1297135137;

	/**
	 * Setter for <code>incomb.user.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>incomb.user.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>incomb.user.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>incomb.user.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>incomb.user.username</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>incomb.user.username</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>incomb.user.display_name</code>.
	 */
	public void setDisplayName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>incomb.user.display_name</code>.
	 */
	public java.lang.String getDisplayName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>incomb.user.password_hash</code>.
	 */
	public void setPasswordHash(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>incomb.user.password_hash</code>.
	 */
	public java.lang.String getPasswordHash() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>incomb.user.salt</code>.
	 */
	public void setSalt(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>incomb.user.salt</code>.
	 */
	public java.lang.String getSalt() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>incomb.user.register_date</code>.
	 */
	public void setRegisterDate(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>incomb.user.register_date</code>.
	 */
	public java.sql.Timestamp getRegisterDate() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>incomb.user.deleted</code>.
	 */
	public void setDeleted(java.lang.Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>incomb.user.deleted</code>.
	 */
	public java.lang.Boolean getDeleted() {
		return (java.lang.Boolean) getValue(7);
	}

	/**
	 * Setter for <code>incomb.user.private_profile</code>.
	 */
	public void setPrivateProfile(java.lang.Boolean value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>incomb.user.private_profile</code>.
	 */
	public java.lang.Boolean getPrivateProfile() {
		return (java.lang.Boolean) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Boolean, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Boolean, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.incomb.server.model.tables.UserTable.USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.incomb.server.model.tables.UserTable.USER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.incomb.server.model.tables.UserTable.USER.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.incomb.server.model.tables.UserTable.USER.DISPLAY_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.incomb.server.model.tables.UserTable.USER.PASSWORD_HASH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.incomb.server.model.tables.UserTable.USER.SALT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return com.incomb.server.model.tables.UserTable.USER.REGISTER_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return com.incomb.server.model.tables.UserTable.USER.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field9() {
		return com.incomb.server.model.tables.UserTable.USER.PRIVATE_PROFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDisplayName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getPasswordHash();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSalt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getRegisterDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value9() {
		return getPrivateProfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value2(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value3(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value4(java.lang.String value) {
		setDisplayName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value5(java.lang.String value) {
		setPasswordHash(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value6(java.lang.String value) {
		setSalt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value7(java.sql.Timestamp value) {
		setRegisterDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value8(java.lang.Boolean value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value9(java.lang.Boolean value) {
		setPrivateProfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.sql.Timestamp value7, java.lang.Boolean value8, java.lang.Boolean value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(com.incomb.server.model.tables.UserTable.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(java.lang.Long id, java.lang.String email, java.lang.String username, java.lang.String displayName, java.lang.String passwordHash, java.lang.String salt, java.sql.Timestamp registerDate, java.lang.Boolean deleted, java.lang.Boolean privateProfile) {
		super(com.incomb.server.model.tables.UserTable.USER);

		setValue(0, id);
		setValue(1, email);
		setValue(2, username);
		setValue(3, displayName);
		setValue(4, passwordHash);
		setValue(5, salt);
		setValue(6, registerDate);
		setValue(7, deleted);
		setValue(8, privateProfile);
	}
}
