/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalProviderDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.ProviderRecord, com.incomb.server.model.Provider, java.lang.Integer> {

	/**
	 * Create a new InternalProviderDao without any configuration
	 */
	public InternalProviderDao() {
		super(com.incomb.server.model.tables.ProviderTable.PROVIDER, com.incomb.server.model.Provider.class);
	}

	/**
	 * Create a new InternalProviderDao with an attached configuration
	 */
	public InternalProviderDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.ProviderTable.PROVIDER, com.incomb.server.model.Provider.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.incomb.server.model.Provider object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Provider> fetchById(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.ProviderTable.PROVIDER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.incomb.server.model.Provider fetchOneById(java.lang.Integer value) {
		return fetchOne(com.incomb.server.model.tables.ProviderTable.PROVIDER.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Provider> fetchByName(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ProviderTable.PROVIDER.NAME, values);
	}

	/**
	 * Fetch records that have <code>image_path IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Provider> fetchByImagePath(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ProviderTable.PROVIDER.IMAGE_PATH, values);
	}

	/**
	 * Fetch records that have <code>website IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Provider> fetchByWebsite(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ProviderTable.PROVIDER.WEBSITE, values);
	}

	/**
	 * Fetch records that have <code>parser_class IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Provider> fetchByParserClass(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ProviderTable.PROVIDER.PARSER_CLASS, values);
	}
}
