/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalPermissionDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.PermissionRecord, com.incomb.server.model.Permission, java.lang.Integer> {

	/**
	 * Create a new InternalPermissionDao without any configuration
	 */
	public InternalPermissionDao() {
		super(com.incomb.server.model.tables.PermissionTable.PERMISSION, com.incomb.server.model.Permission.class);
	}

	/**
	 * Create a new InternalPermissionDao with an attached configuration
	 */
	public InternalPermissionDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.PermissionTable.PERMISSION, com.incomb.server.model.Permission.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.incomb.server.model.Permission object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Permission> fetchById(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.PermissionTable.PERMISSION.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.incomb.server.model.Permission fetchOneById(java.lang.Integer value) {
		return fetchOne(com.incomb.server.model.tables.PermissionTable.PERMISSION.ID, value);
	}

	/**
	 * Fetch records that have <code>name_key IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Permission> fetchByNameKey(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.PermissionTable.PERMISSION.NAME_KEY, values);
	}
}
