/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalModuleDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.ModuleRecord, com.incomb.server.model.Module, java.lang.Integer> {

	/**
	 * Create a new InternalModuleDao without any configuration
	 */
	public InternalModuleDao() {
		super(com.incomb.server.model.tables.ModuleTable.MODULE, com.incomb.server.model.Module.class);
	}

	/**
	 * Create a new InternalModuleDao with an attached configuration
	 */
	public InternalModuleDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.ModuleTable.MODULE, com.incomb.server.model.Module.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.incomb.server.model.Module object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Module> fetchById(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.ModuleTable.MODULE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.incomb.server.model.Module fetchOneById(java.lang.Integer value) {
		return fetchOne(com.incomb.server.model.tables.ModuleTable.MODULE.ID, value);
	}

	/**
	 * Fetch records that have <code>name_key IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Module> fetchByNameKey(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ModuleTable.MODULE.NAME_KEY, values);
	}

	/**
	 * Fetch records that have <code>image_path IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Module> fetchByImagePath(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ModuleTable.MODULE.IMAGE_PATH, values);
	}

	/**
	 * Fetch records that have <code>template_path IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Module> fetchByTemplatePath(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ModuleTable.MODULE.TEMPLATE_PATH, values);
	}
}
