/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalRssFeedContentSourceDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.RssFeedContentSourceRecord, com.incomb.server.model.RssFeedContentSource, java.lang.Integer> {

	/**
	 * Create a new InternalRssFeedContentSourceDao without any configuration
	 */
	public InternalRssFeedContentSourceDao() {
		super(com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE, com.incomb.server.model.RssFeedContentSource.class);
	}

	/**
	 * Create a new InternalRssFeedContentSourceDao with an attached configuration
	 */
	public InternalRssFeedContentSourceDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE, com.incomb.server.model.RssFeedContentSource.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.incomb.server.model.RssFeedContentSource object) {
		return object.getContentSourceId();
	}

	/**
	 * Fetch records that have <code>content_source_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.RssFeedContentSource> fetchByContentSourceId(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE.CONTENT_SOURCE_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>content_source_id = value</code>
	 */
	public com.incomb.server.model.RssFeedContentSource fetchOneByContentSourceId(java.lang.Integer value) {
		return fetchOne(com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE.CONTENT_SOURCE_ID, value);
	}
}
