/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalCategoryDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.CategoryRecord, com.incomb.server.model.Category, java.lang.Integer> {

	/**
	 * Create a new InternalCategoryDao without any configuration
	 */
	public InternalCategoryDao() {
		super(com.incomb.server.model.tables.CategoryTable.CATEGORY, com.incomb.server.model.Category.class);
	}

	/**
	 * Create a new InternalCategoryDao with an attached configuration
	 */
	public InternalCategoryDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.CategoryTable.CATEGORY, com.incomb.server.model.Category.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.incomb.server.model.Category object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Category> fetchById(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.CategoryTable.CATEGORY.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.incomb.server.model.Category fetchOneById(java.lang.Integer value) {
		return fetchOne(com.incomb.server.model.tables.CategoryTable.CATEGORY.ID, value);
	}

	/**
	 * Fetch records that have <code>name_key IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Category> fetchByNameKey(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.CategoryTable.CATEGORY.NAME_KEY, values);
	}

	/**
	 * Fetch records that have <code>image_path IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Category> fetchByImagePath(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.CategoryTable.CATEGORY.IMAGE_PATH, values);
	}

	/**
	 * Fetch records that have <code>module_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Category> fetchByModuleId(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.CategoryTable.CATEGORY.MODULE_ID, values);
	}
}
