/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalUserLocaleDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.UserLocaleRecord, com.incomb.server.model.UserLocale, org.jooq.Record2<java.lang.Long, java.lang.String>> {

	/**
	 * Create a new InternalUserLocaleDao without any configuration
	 */
	public InternalUserLocaleDao() {
		super(com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE, com.incomb.server.model.UserLocale.class);
	}

	/**
	 * Create a new InternalUserLocaleDao with an attached configuration
	 */
	public InternalUserLocaleDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE, com.incomb.server.model.UserLocale.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record2<java.lang.Long, java.lang.String> getId(com.incomb.server.model.UserLocale object) {
		return compositeKeyRecord(object.getUserId(), object.getLocale());
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.UserLocale> fetchByUserId(java.lang.Long... values) {
		return fetch(com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>locale IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.UserLocale> fetchByLocale(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE.LOCALE, values);
	}
}
