/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalContentVoteDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.ContentVoteRecord, com.incomb.server.model.ContentVote, org.jooq.Record2<java.lang.Long, java.lang.Long>> {

	/**
	 * Create a new InternalContentVoteDao without any configuration
	 */
	public InternalContentVoteDao() {
		super(com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE, com.incomb.server.model.ContentVote.class);
	}

	/**
	 * Create a new InternalContentVoteDao with an attached configuration
	 */
	public InternalContentVoteDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE, com.incomb.server.model.ContentVote.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record2<java.lang.Long, java.lang.Long> getId(com.incomb.server.model.ContentVote object) {
		return compositeKeyRecord(object.getUserId(), object.getContentId());
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.ContentVote> fetchByUserId(java.lang.Long... values) {
		return fetch(com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>content_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.ContentVote> fetchByContentId(java.lang.Long... values) {
		return fetch(com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.CONTENT_ID, values);
	}

	/**
	 * Fetch records that have <code>vote_date IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.ContentVote> fetchByVoteDate(java.sql.Timestamp... values) {
		return fetch(com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.VOTE_DATE, values);
	}

	/**
	 * Fetch records that have <code>up IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.ContentVote> fetchByUp(java.lang.Boolean... values) {
		return fetch(com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.UP, values);
	}
}
