/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalContentDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.ContentRecord, com.incomb.server.model.Content, java.lang.Long> {

	/**
	 * Create a new InternalContentDao without any configuration
	 */
	public InternalContentDao() {
		super(com.incomb.server.model.tables.ContentTable.CONTENT, com.incomb.server.model.Content.class);
	}

	/**
	 * Create a new InternalContentDao with an attached configuration
	 */
	public InternalContentDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.ContentTable.CONTENT, com.incomb.server.model.Content.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.incomb.server.model.Content object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Content> fetchById(java.lang.Long... values) {
		return fetch(com.incomb.server.model.tables.ContentTable.CONTENT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.incomb.server.model.Content fetchOneById(java.lang.Long value) {
		return fetchOne(com.incomb.server.model.tables.ContentTable.CONTENT.ID, value);
	}

	/**
	 * Fetch records that have <code>provider_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Content> fetchByProviderId(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.ContentTable.CONTENT.PROVIDER_ID, values);
	}

	/**
	 * Fetch records that have <code>category_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Content> fetchByCategoryId(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.ContentTable.CONTENT.CATEGORY_ID, values);
	}

	/**
	 * Fetch records that have <code>title IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Content> fetchByTitle(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ContentTable.CONTENT.TITLE, values);
	}

	/**
	 * Fetch records that have <code>locale IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Content> fetchByLocale(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ContentTable.CONTENT.LOCALE, values);
	}

	/**
	 * Fetch records that have <code>text IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Content> fetchByText(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ContentTable.CONTENT.TEXT, values);
	}

	/**
	 * Fetch records that have <code>publish_date IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Content> fetchByPublishDate(java.sql.Timestamp... values) {
		return fetch(com.incomb.server.model.tables.ContentTable.CONTENT.PUBLISH_DATE, values);
	}

	/**
	 * Fetch records that have <code>indexed IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Content> fetchByIndexed(java.lang.Boolean... values) {
		return fetch(com.incomb.server.model.tables.ContentTable.CONTENT.INDEXED, values);
	}
}
