/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalContentSourceDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.ContentSourceRecord, com.incomb.server.model.ContentSource, java.lang.Integer> {

	/**
	 * Create a new InternalContentSourceDao without any configuration
	 */
	public InternalContentSourceDao() {
		super(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE, com.incomb.server.model.ContentSource.class);
	}

	/**
	 * Create a new InternalContentSourceDao with an attached configuration
	 */
	public InternalContentSourceDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE, com.incomb.server.model.ContentSource.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.incomb.server.model.ContentSource object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.ContentSource> fetchById(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.incomb.server.model.ContentSource fetchOneById(java.lang.Integer value) {
		return fetchOne(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.ID, value);
	}

	/**
	 * Fetch records that have <code>provider_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.ContentSource> fetchByProviderId(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.PROVIDER_ID, values);
	}

	/**
	 * Fetch records that have <code>category_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.ContentSource> fetchByCategoryId(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.CATEGORY_ID, values);
	}

	/**
	 * Fetch records that have <code>interval IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.ContentSource> fetchByInterval(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.INTERVAL, values);
	}

	/**
	 * Fetch records that have <code>url IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.ContentSource> fetchByUrl(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.URL, values);
	}

	/**
	 * Fetch records that have <code>locale IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.ContentSource> fetchByLocale(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.LOCALE, values);
	}
}
