/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalTagPreferenceDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.TagPreferenceRecord, com.incomb.server.model.TagPreference, org.jooq.Record2<java.lang.Long, java.lang.String>> {

	/**
	 * Create a new InternalTagPreferenceDao without any configuration
	 */
	public InternalTagPreferenceDao() {
		super(com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE, com.incomb.server.model.TagPreference.class);
	}

	/**
	 * Create a new InternalTagPreferenceDao with an attached configuration
	 */
	public InternalTagPreferenceDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE, com.incomb.server.model.TagPreference.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record2<java.lang.Long, java.lang.String> getId(com.incomb.server.model.TagPreference object) {
		return compositeKeyRecord(object.getUserId(), object.getTag());
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.TagPreference> fetchByUserId(java.lang.Long... values) {
		return fetch(com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>tag IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.TagPreference> fetchByTag(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE.TAG, values);
	}
}
