/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalNewsDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.NewsRecord, com.incomb.server.model.News, java.lang.Long> {

	/**
	 * Create a new InternalNewsDao without any configuration
	 */
	public InternalNewsDao() {
		super(com.incomb.server.model.tables.NewsTable.NEWS, com.incomb.server.model.News.class);
	}

	/**
	 * Create a new InternalNewsDao with an attached configuration
	 */
	public InternalNewsDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.NewsTable.NEWS, com.incomb.server.model.News.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.incomb.server.model.News object) {
		return object.getContentId();
	}

	/**
	 * Fetch records that have <code>content_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.News> fetchByContentId(java.lang.Long... values) {
		return fetch(com.incomb.server.model.tables.NewsTable.NEWS.CONTENT_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>content_id = value</code>
	 */
	public com.incomb.server.model.News fetchOneByContentId(java.lang.Long value) {
		return fetchOne(com.incomb.server.model.tables.NewsTable.NEWS.CONTENT_ID, value);
	}

	/**
	 * Fetch records that have <code>link IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.News> fetchByLink(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.NewsTable.NEWS.LINK, values);
	}

	/**
	 * Fetch records that have <code>image_url IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.News> fetchByImageUrl(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.NewsTable.NEWS.IMAGE_URL, values);
	}

	/**
	 * Fetch records that have <code>image_width IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.News> fetchByImageWidth(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.NewsTable.NEWS.IMAGE_WIDTH, values);
	}

	/**
	 * Fetch records that have <code>image_height IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.News> fetchByImageHeight(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.NewsTable.NEWS.IMAGE_HEIGHT, values);
	}

	/**
	 * Fetch records that have <code>news_group_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.News> fetchByNewsGroupId(java.lang.Long... values) {
		return fetch(com.incomb.server.model.tables.NewsTable.NEWS.NEWS_GROUP_ID, values);
	}
}
