/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalUserDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.UserRecord, com.incomb.server.model.User, java.lang.Long> {

	/**
	 * Create a new InternalUserDao without any configuration
	 */
	public InternalUserDao() {
		super(com.incomb.server.model.tables.UserTable.USER, com.incomb.server.model.User.class);
	}

	/**
	 * Create a new InternalUserDao with an attached configuration
	 */
	public InternalUserDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.UserTable.USER, com.incomb.server.model.User.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.incomb.server.model.User object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.User> fetchById(java.lang.Long... values) {
		return fetch(com.incomb.server.model.tables.UserTable.USER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.incomb.server.model.User fetchOneById(java.lang.Long value) {
		return fetchOne(com.incomb.server.model.tables.UserTable.USER.ID, value);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.User> fetchByEmail(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.UserTable.USER.EMAIL, values);
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.User> fetchByUsername(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.UserTable.USER.USERNAME, values);
	}

	/**
	 * Fetch a unique record that has <code>username = value</code>
	 */
	public com.incomb.server.model.User fetchOneByUsername(java.lang.String value) {
		return fetchOne(com.incomb.server.model.tables.UserTable.USER.USERNAME, value);
	}

	/**
	 * Fetch records that have <code>display_name IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.User> fetchByDisplayName(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.UserTable.USER.DISPLAY_NAME, values);
	}

	/**
	 * Fetch records that have <code>password_hash IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.User> fetchByPasswordHash(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.UserTable.USER.PASSWORD_HASH, values);
	}

	/**
	 * Fetch records that have <code>salt IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.User> fetchBySalt(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.UserTable.USER.SALT, values);
	}

	/**
	 * Fetch records that have <code>register_date IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.User> fetchByRegisterDate(java.sql.Timestamp... values) {
		return fetch(com.incomb.server.model.tables.UserTable.USER.REGISTER_DATE, values);
	}

	/**
	 * Fetch records that have <code>deleted IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.User> fetchByDeleted(java.lang.Boolean... values) {
		return fetch(com.incomb.server.model.tables.UserTable.USER.DELETED, values);
	}

	/**
	 * Fetch records that have <code>private_profile IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.User> fetchByPrivateProfile(java.lang.Boolean... values) {
		return fetch(com.incomb.server.model.tables.UserTable.USER.PRIVATE_PROFILE, values);
	}
}
