/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalCombItemDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.CombItemRecord, com.incomb.server.model.CombItem, org.jooq.Record2<java.lang.Long, java.lang.Long>> {

	/**
	 * Create a new InternalCombItemDao without any configuration
	 */
	public InternalCombItemDao() {
		super(com.incomb.server.model.tables.CombItemTable.COMB_ITEM, com.incomb.server.model.CombItem.class);
	}

	/**
	 * Create a new InternalCombItemDao with an attached configuration
	 */
	public InternalCombItemDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.CombItemTable.COMB_ITEM, com.incomb.server.model.CombItem.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record2<java.lang.Long, java.lang.Long> getId(com.incomb.server.model.CombItem object) {
		return compositeKeyRecord(object.getUserId(), object.getContentId());
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.CombItem> fetchByUserId(java.lang.Long... values) {
		return fetch(com.incomb.server.model.tables.CombItemTable.COMB_ITEM.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>content_id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.CombItem> fetchByContentId(java.lang.Long... values) {
		return fetch(com.incomb.server.model.tables.CombItemTable.COMB_ITEM.CONTENT_ID, values);
	}

	/**
	 * Fetch records that have <code>add_date IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.CombItem> fetchByAddDate(java.sql.Timestamp... values) {
		return fetch(com.incomb.server.model.tables.CombItemTable.COMB_ITEM.ADD_DATE, values);
	}

	/**
	 * Fetch records that have <code>read_date IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.CombItem> fetchByReadDate(java.sql.Timestamp... values) {
		return fetch(com.incomb.server.model.tables.CombItemTable.COMB_ITEM.READ_DATE, values);
	}
}
