/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.dao.internal;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalRoleDao extends org.jooq.impl.DAOImpl<com.incomb.server.model.records.RoleRecord, com.incomb.server.model.Role, java.lang.Integer> {

	/**
	 * Create a new InternalRoleDao without any configuration
	 */
	public InternalRoleDao() {
		super(com.incomb.server.model.tables.RoleTable.ROLE, com.incomb.server.model.Role.class);
	}

	/**
	 * Create a new InternalRoleDao with an attached configuration
	 */
	public InternalRoleDao(org.jooq.Configuration configuration) {
		super(com.incomb.server.model.tables.RoleTable.ROLE, com.incomb.server.model.Role.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.incomb.server.model.Role object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Role> fetchById(java.lang.Integer... values) {
		return fetch(com.incomb.server.model.tables.RoleTable.ROLE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.incomb.server.model.Role fetchOneById(java.lang.Integer value) {
		return fetchOne(com.incomb.server.model.tables.RoleTable.ROLE.ID, value);
	}

	/**
	 * Fetch records that have <code>name_key IN (values)</code>
	 */
	public java.util.List<com.incomb.server.model.Role> fetchByNameKey(java.lang.String... values) {
		return fetch(com.incomb.server.model.tables.RoleTable.ROLE.NAME_KEY, values);
	}
}
