/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryPreferenceTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.CategoryPreferenceRecord> {

	private static final long serialVersionUID = -593966480;

	/**
	 * The reference instance of <code>incomb.category_preference</code>
	 */
	public static final com.incomb.server.model.tables.CategoryPreferenceTable CATEGORY_PREFERENCE = new com.incomb.server.model.tables.CategoryPreferenceTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.CategoryPreferenceRecord> getRecordType() {
		return com.incomb.server.model.records.CategoryPreferenceRecord.class;
	}

	/**
	 * The column <code>incomb.category_preference.user_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CategoryPreferenceRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.category_preference.category_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CategoryPreferenceRecord, java.lang.Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.category_preference.factor</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CategoryPreferenceRecord, java.lang.Double> FACTOR = createField("factor", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

	/**
	 * Create a <code>incomb.category_preference</code> table reference
	 */
	public CategoryPreferenceTable() {
		this("category_preference", null);
	}

	/**
	 * Create an aliased <code>incomb.category_preference</code> table reference
	 */
	public CategoryPreferenceTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE);
	}

	private CategoryPreferenceTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.CategoryPreferenceRecord> aliased) {
		this(alias, aliased, null);
	}

	private CategoryPreferenceTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.CategoryPreferenceRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.CategoryPreferenceRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_CATEGORY_PREFERENCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.CategoryPreferenceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.CategoryPreferenceRecord>>asList(com.incomb.server.model.tables.Keys.KEY_CATEGORY_PREFERENCE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.CategoryPreferenceRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.CategoryPreferenceRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_CATEGORYPREFERENCE_USER1, com.incomb.server.model.tables.Keys.FK_CATEGORYPREFERENCE_CATEGORY1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.CategoryPreferenceTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.CategoryPreferenceTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.CategoryPreferenceTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.CategoryPreferenceTable(name, null);
	}
}
