/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.CategoryRecord> {

	private static final long serialVersionUID = 1129432511;

	/**
	 * The reference instance of <code>incomb.category</code>
	 */
	public static final com.incomb.server.model.tables.CategoryTable CATEGORY = new com.incomb.server.model.tables.CategoryTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.CategoryRecord> getRecordType() {
		return com.incomb.server.model.records.CategoryRecord.class;
	}

	/**
	 * The column <code>incomb.category.id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CategoryRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.category.name_key</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CategoryRecord, java.lang.String> NAME_KEY = createField("name_key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>incomb.category.image_path</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CategoryRecord, java.lang.String> IMAGE_PATH = createField("image_path", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>incomb.category.module_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CategoryRecord, java.lang.Integer> MODULE_ID = createField("module_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>incomb.category</code> table reference
	 */
	public CategoryTable() {
		this("category", null);
	}

	/**
	 * Create an aliased <code>incomb.category</code> table reference
	 */
	public CategoryTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.CategoryTable.CATEGORY);
	}

	private CategoryTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.CategoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private CategoryTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.CategoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.CategoryRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_CATEGORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.CategoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.CategoryRecord>>asList(com.incomb.server.model.tables.Keys.KEY_CATEGORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.CategoryRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.CategoryRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_CATEGORY_MODULE1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.CategoryTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.CategoryTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.CategoryTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.CategoryTable(name, null);
	}
}
