/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CombItemTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.CombItemRecord> {

	private static final long serialVersionUID = -1678309673;

	/**
	 * The reference instance of <code>incomb.comb_Item</code>
	 */
	public static final com.incomb.server.model.tables.CombItemTable COMB_ITEM = new com.incomb.server.model.tables.CombItemTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.CombItemRecord> getRecordType() {
		return com.incomb.server.model.records.CombItemRecord.class;
	}

	/**
	 * The column <code>incomb.comb_Item.user_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CombItemRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.comb_Item.content_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CombItemRecord, java.lang.Long> CONTENT_ID = createField("content_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.comb_Item.add_date</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CombItemRecord, java.sql.Timestamp> ADD_DATE = createField("add_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>incomb.comb_Item.read_date</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.CombItemRecord, java.sql.Timestamp> READ_DATE = createField("read_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>incomb.comb_Item</code> table reference
	 */
	public CombItemTable() {
		this("comb_Item", null);
	}

	/**
	 * Create an aliased <code>incomb.comb_Item</code> table reference
	 */
	public CombItemTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.CombItemTable.COMB_ITEM);
	}

	private CombItemTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.CombItemRecord> aliased) {
		this(alias, aliased, null);
	}

	private CombItemTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.CombItemRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.CombItemRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_COMB_ITEM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.CombItemRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.CombItemRecord>>asList(com.incomb.server.model.tables.Keys.KEY_COMB_ITEM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.CombItemRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.CombItemRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_USER_HAS_CONTENT_USER1, com.incomb.server.model.tables.Keys.FK_USER_HAS_CONTENT_CONTENT1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.CombItemTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.CombItemTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.CombItemTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.CombItemTable(name, null);
	}
}
