/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentSourceTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.ContentSourceRecord> {

	private static final long serialVersionUID = -191367463;

	/**
	 * The reference instance of <code>incomb.content_source</code>
	 */
	public static final com.incomb.server.model.tables.ContentSourceTable CONTENT_SOURCE = new com.incomb.server.model.tables.ContentSourceTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.ContentSourceRecord> getRecordType() {
		return com.incomb.server.model.records.ContentSourceRecord.class;
	}

	/**
	 * The column <code>incomb.content_source.id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentSourceRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_source.provider_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentSourceRecord, java.lang.Integer> PROVIDER_ID = createField("provider_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_source.category_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentSourceRecord, java.lang.Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_source.interval</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentSourceRecord, java.lang.Integer> INTERVAL = createField("interval", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_source.url</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentSourceRecord, java.lang.String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>incomb.content_source.locale</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentSourceRecord, java.lang.String> LOCALE = createField("locale", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

	/**
	 * Create a <code>incomb.content_source</code> table reference
	 */
	public ContentSourceTable() {
		this("content_source", null);
	}

	/**
	 * Create an aliased <code>incomb.content_source</code> table reference
	 */
	public ContentSourceTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE);
	}

	private ContentSourceTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ContentSourceRecord> aliased) {
		this(alias, aliased, null);
	}

	private ContentSourceTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ContentSourceRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.ContentSourceRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_CONTENT_SOURCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.ContentSourceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.ContentSourceRecord>>asList(com.incomb.server.model.tables.Keys.KEY_CONTENT_SOURCE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.ContentSourceRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.ContentSourceRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_CONTENTSOURCE_PROVIDER1, com.incomb.server.model.tables.Keys.FK_CONTENTSOURCE_CATEGORY1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.ContentSourceTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.ContentSourceTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.ContentSourceTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.ContentSourceTable(name, null);
	}
}
