/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentVoteTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.ContentVoteRecord> {

	private static final long serialVersionUID = 1326589810;

	/**
	 * The reference instance of <code>incomb.content_vote</code>
	 */
	public static final com.incomb.server.model.tables.ContentVoteTable CONTENT_VOTE = new com.incomb.server.model.tables.ContentVoteTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.ContentVoteRecord> getRecordType() {
		return com.incomb.server.model.records.ContentVoteRecord.class;
	}

	/**
	 * The column <code>incomb.content_vote.user_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentVoteRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_vote.content_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentVoteRecord, java.lang.Long> CONTENT_ID = createField("content_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_vote.vote_date</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentVoteRecord, java.sql.Timestamp> VOTE_DATE = createField("vote_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_vote.up</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentVoteRecord, java.lang.Boolean> UP = createField("up", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * Create a <code>incomb.content_vote</code> table reference
	 */
	public ContentVoteTable() {
		this("content_vote", null);
	}

	/**
	 * Create an aliased <code>incomb.content_vote</code> table reference
	 */
	public ContentVoteTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE);
	}

	private ContentVoteTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ContentVoteRecord> aliased) {
		this(alias, aliased, null);
	}

	private ContentVoteTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ContentVoteRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.ContentVoteRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_CONTENT_VOTE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.ContentVoteRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.ContentVoteRecord>>asList(com.incomb.server.model.tables.Keys.KEY_CONTENT_VOTE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.ContentVoteRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.ContentVoteRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_CONTENTVOTE_USER1, com.incomb.server.model.tables.Keys.FK_CONTENTVOTE_CONTENT1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.ContentVoteTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.ContentVoteTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.ContentVoteTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.ContentVoteTable(name, null);
	}
}
