/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentCommentTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.ContentCommentRecord> {

	private static final long serialVersionUID = 782389101;

	/**
	 * The reference instance of <code>incomb.content_comment</code>
	 */
	public static final com.incomb.server.model.tables.ContentCommentTable CONTENT_COMMENT = new com.incomb.server.model.tables.ContentCommentTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.ContentCommentRecord> getRecordType() {
		return com.incomb.server.model.records.ContentCommentRecord.class;
	}

	/**
	 * The column <code>incomb.content_comment.id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentCommentRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_comment.user_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentCommentRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_comment.content_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentCommentRecord, java.lang.Long> CONTENT_ID = createField("content_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_comment.comment_date</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentCommentRecord, java.sql.Timestamp> COMMENT_DATE = createField("comment_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>incomb.content_comment.comment</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ContentCommentRecord, java.lang.String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.CLOB.length(16777215).nullable(false), this, "");

	/**
	 * Create a <code>incomb.content_comment</code> table reference
	 */
	public ContentCommentTable() {
		this("content_comment", null);
	}

	/**
	 * Create an aliased <code>incomb.content_comment</code> table reference
	 */
	public ContentCommentTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT);
	}

	private ContentCommentTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ContentCommentRecord> aliased) {
		this(alias, aliased, null);
	}

	private ContentCommentTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ContentCommentRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.incomb.server.model.records.ContentCommentRecord, java.lang.Long> getIdentity() {
		return com.incomb.server.model.tables.Keys.IDENTITY_CONTENT_COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.ContentCommentRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_CONTENT_COMMENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.ContentCommentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.ContentCommentRecord>>asList(com.incomb.server.model.tables.Keys.KEY_CONTENT_COMMENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.ContentCommentRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.ContentCommentRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_CONTENTCOMMENT_USER1, com.incomb.server.model.tables.Keys.FK_CONTENTCOMMENT_CONTENT1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.ContentCommentTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.ContentCommentTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.ContentCommentTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.ContentCommentTable(name, null);
	}
}
