/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FetchHistoryTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.FetchHistoryRecord> {

	private static final long serialVersionUID = -865503106;

	/**
	 * The reference instance of <code>incomb.fetch_history</code>
	 */
	public static final com.incomb.server.model.tables.FetchHistoryTable FETCH_HISTORY = new com.incomb.server.model.tables.FetchHistoryTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.FetchHistoryRecord> getRecordType() {
		return com.incomb.server.model.records.FetchHistoryRecord.class;
	}

	/**
	 * The column <code>incomb.fetch_history.content_source_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.FetchHistoryRecord, java.lang.Integer> CONTENT_SOURCE_ID = createField("content_source_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.fetch_history.fetch_time</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.FetchHistoryRecord, java.sql.Timestamp> FETCH_TIME = createField("fetch_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>incomb.fetch_history.result</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.FetchHistoryRecord, java.lang.Boolean> RESULT = createField("result", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * Create a <code>incomb.fetch_history</code> table reference
	 */
	public FetchHistoryTable() {
		this("fetch_history", null);
	}

	/**
	 * Create an aliased <code>incomb.fetch_history</code> table reference
	 */
	public FetchHistoryTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.FetchHistoryTable.FETCH_HISTORY);
	}

	private FetchHistoryTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.FetchHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private FetchHistoryTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.FetchHistoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.FetchHistoryRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_FETCH_HISTORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.FetchHistoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.FetchHistoryRecord>>asList(com.incomb.server.model.tables.Keys.KEY_FETCH_HISTORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.FetchHistoryRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.FetchHistoryRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_FETCHHISTORY_CONTENTSOURCE1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.FetchHistoryTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.FetchHistoryTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.FetchHistoryTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.FetchHistoryTable(name, null);
	}
}
