/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlyWithTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.FlyWithRecord> {

	private static final long serialVersionUID = 408733163;

	/**
	 * The reference instance of <code>incomb.fly_with</code>
	 */
	public static final com.incomb.server.model.tables.FlyWithTable FLY_WITH = new com.incomb.server.model.tables.FlyWithTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.FlyWithRecord> getRecordType() {
		return com.incomb.server.model.records.FlyWithRecord.class;
	}

	/**
	 * The column <code>incomb.fly_with.user_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.FlyWithRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.fly_with.fly_with_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.FlyWithRecord, java.lang.Long> FLY_WITH_ID = createField("fly_with_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.fly_with.fly_with_start_date</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.FlyWithRecord, java.sql.Timestamp> FLY_WITH_START_DATE = createField("fly_with_start_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>incomb.fly_with</code> table reference
	 */
	public FlyWithTable() {
		this("fly_with", null);
	}

	/**
	 * Create an aliased <code>incomb.fly_with</code> table reference
	 */
	public FlyWithTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.FlyWithTable.FLY_WITH);
	}

	private FlyWithTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.FlyWithRecord> aliased) {
		this(alias, aliased, null);
	}

	private FlyWithTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.FlyWithRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.FlyWithRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_FLY_WITH_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.FlyWithRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.FlyWithRecord>>asList(com.incomb.server.model.tables.Keys.KEY_FLY_WITH_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.FlyWithRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.FlyWithRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_USER_HAS_USER_USER1, com.incomb.server.model.tables.Keys.FK_USER_HAS_USER_USER2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.FlyWithTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.FlyWithTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.FlyWithTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.FlyWithTable(name, null);
	}
}
