/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IncombTable extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -391208363;

	/**
	 * The reference instance of <code>incomb</code>
	 */
	public static final IncombTable INCOMB = new IncombTable();

	/**
	 * No further instances allowed
	 */
	private IncombTable() {
		super("incomb");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.incomb.server.model.tables.CategoryTable.CATEGORY,
			com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE,
			com.incomb.server.model.tables.CombItemTable.COMB_ITEM,
			com.incomb.server.model.tables.ContentTable.CONTENT,
			com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT,
			com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE,
			com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE,
			com.incomb.server.model.tables.FetchHistoryTable.FETCH_HISTORY,
			com.incomb.server.model.tables.FlyWithTable.FLY_WITH,
			com.incomb.server.model.tables.ModuleTable.MODULE,
			com.incomb.server.model.tables.NewsTable.NEWS,
			com.incomb.server.model.tables.PermissionTable.PERMISSION,
			com.incomb.server.model.tables.ProviderTable.PROVIDER,
			com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION,
			com.incomb.server.model.tables.RoleTable.ROLE,
			com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION,
			com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE,
			com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE,
			com.incomb.server.model.tables.UserTable.USER,
			com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE,
			com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE);
	}
}
