/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * A class modelling foreign key relationships between tables of the <code>incomb</code> 
 * schema
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.incomb.server.model.records.ContentRecord, java.lang.Long> IDENTITY_CONTENT = Identities0.IDENTITY_CONTENT;
	public static final org.jooq.Identity<com.incomb.server.model.records.ContentCommentRecord, java.lang.Long> IDENTITY_CONTENT_COMMENT = Identities0.IDENTITY_CONTENT_COMMENT;
	public static final org.jooq.Identity<com.incomb.server.model.records.UserRecord, java.lang.Long> IDENTITY_USER = Identities0.IDENTITY_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.incomb.server.model.records.CategoryRecord> KEY_CATEGORY_PRIMARY = UniqueKeys0.KEY_CATEGORY_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.CategoryPreferenceRecord> KEY_CATEGORY_PREFERENCE_PRIMARY = UniqueKeys0.KEY_CATEGORY_PREFERENCE_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.CombItemRecord> KEY_COMB_ITEM_PRIMARY = UniqueKeys0.KEY_COMB_ITEM_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.ContentRecord> KEY_CONTENT_PRIMARY = UniqueKeys0.KEY_CONTENT_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.ContentCommentRecord> KEY_CONTENT_COMMENT_PRIMARY = UniqueKeys0.KEY_CONTENT_COMMENT_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.ContentSourceRecord> KEY_CONTENT_SOURCE_PRIMARY = UniqueKeys0.KEY_CONTENT_SOURCE_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.ContentVoteRecord> KEY_CONTENT_VOTE_PRIMARY = UniqueKeys0.KEY_CONTENT_VOTE_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.FetchHistoryRecord> KEY_FETCH_HISTORY_PRIMARY = UniqueKeys0.KEY_FETCH_HISTORY_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.FlyWithRecord> KEY_FLY_WITH_PRIMARY = UniqueKeys0.KEY_FLY_WITH_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.ModuleRecord> KEY_MODULE_PRIMARY = UniqueKeys0.KEY_MODULE_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.NewsRecord> KEY_NEWS_PRIMARY = UniqueKeys0.KEY_NEWS_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.PermissionRecord> KEY_PERMISSION_PRIMARY = UniqueKeys0.KEY_PERMISSION_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.ProviderRecord> KEY_PROVIDER_PRIMARY = UniqueKeys0.KEY_PROVIDER_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.ProviderExclusionRecord> KEY_PROVIDER_EXCLUSION_PRIMARY = UniqueKeys0.KEY_PROVIDER_EXCLUSION_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.RoleRecord> KEY_ROLE_PRIMARY = UniqueKeys0.KEY_ROLE_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.RoleNmPermissionRecord> KEY_ROLE_NM_PERMISSION_PRIMARY = UniqueKeys0.KEY_ROLE_NM_PERMISSION_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.RssFeedContentSourceRecord> KEY_RSS_FEED_CONTENT_SOURCE_PRIMARY = UniqueKeys0.KEY_RSS_FEED_CONTENT_SOURCE_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.TagPreferenceRecord> KEY_TAG_PREFERENCE_PRIMARY = UniqueKeys0.KEY_TAG_PREFERENCE_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.UserRecord> KEY_USER_USERNAME_UNIQUE = UniqueKeys0.KEY_USER_USERNAME_UNIQUE;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.UserLocaleRecord> KEY_USER_LOCALE_PRIMARY = UniqueKeys0.KEY_USER_LOCALE_PRIMARY;
	public static final org.jooq.UniqueKey<com.incomb.server.model.records.UserNmRoleRecord> KEY_USER_NM_ROLE_PRIMARY = UniqueKeys0.KEY_USER_NM_ROLE_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.incomb.server.model.records.CategoryRecord, com.incomb.server.model.records.ModuleRecord> FK_CATEGORY_MODULE1 = ForeignKeys0.FK_CATEGORY_MODULE1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.CategoryPreferenceRecord, com.incomb.server.model.records.UserRecord> FK_CATEGORYPREFERENCE_USER1 = ForeignKeys0.FK_CATEGORYPREFERENCE_USER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.CategoryPreferenceRecord, com.incomb.server.model.records.CategoryRecord> FK_CATEGORYPREFERENCE_CATEGORY1 = ForeignKeys0.FK_CATEGORYPREFERENCE_CATEGORY1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.CombItemRecord, com.incomb.server.model.records.UserRecord> FK_USER_HAS_CONTENT_USER1 = ForeignKeys0.FK_USER_HAS_CONTENT_USER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.CombItemRecord, com.incomb.server.model.records.ContentRecord> FK_USER_HAS_CONTENT_CONTENT1 = ForeignKeys0.FK_USER_HAS_CONTENT_CONTENT1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentRecord, com.incomb.server.model.records.ProviderRecord> FK_CONTENT_PROVIDER1 = ForeignKeys0.FK_CONTENT_PROVIDER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentRecord, com.incomb.server.model.records.CategoryRecord> FK_CONTENT_CATEGORY1 = ForeignKeys0.FK_CONTENT_CATEGORY1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentCommentRecord, com.incomb.server.model.records.UserRecord> FK_CONTENTCOMMENT_USER1 = ForeignKeys0.FK_CONTENTCOMMENT_USER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentCommentRecord, com.incomb.server.model.records.ContentRecord> FK_CONTENTCOMMENT_CONTENT1 = ForeignKeys0.FK_CONTENTCOMMENT_CONTENT1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentSourceRecord, com.incomb.server.model.records.ProviderRecord> FK_CONTENTSOURCE_PROVIDER1 = ForeignKeys0.FK_CONTENTSOURCE_PROVIDER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentSourceRecord, com.incomb.server.model.records.CategoryRecord> FK_CONTENTSOURCE_CATEGORY1 = ForeignKeys0.FK_CONTENTSOURCE_CATEGORY1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentVoteRecord, com.incomb.server.model.records.UserRecord> FK_CONTENTVOTE_USER1 = ForeignKeys0.FK_CONTENTVOTE_USER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentVoteRecord, com.incomb.server.model.records.ContentRecord> FK_CONTENTVOTE_CONTENT1 = ForeignKeys0.FK_CONTENTVOTE_CONTENT1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.FetchHistoryRecord, com.incomb.server.model.records.ContentSourceRecord> FK_FETCHHISTORY_CONTENTSOURCE1 = ForeignKeys0.FK_FETCHHISTORY_CONTENTSOURCE1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.FlyWithRecord, com.incomb.server.model.records.UserRecord> FK_USER_HAS_USER_USER1 = ForeignKeys0.FK_USER_HAS_USER_USER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.FlyWithRecord, com.incomb.server.model.records.UserRecord> FK_USER_HAS_USER_USER2 = ForeignKeys0.FK_USER_HAS_USER_USER2;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.NewsRecord, com.incomb.server.model.records.ContentRecord> FK_NEWS_CONTENT1 = ForeignKeys0.FK_NEWS_CONTENT1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ProviderExclusionRecord, com.incomb.server.model.records.UserRecord> FK_PROVIDEREXCLUSION_USER1 = ForeignKeys0.FK_PROVIDEREXCLUSION_USER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ProviderExclusionRecord, com.incomb.server.model.records.ProviderRecord> FK_PROVIDEREXCLUSION_PROVIDER1 = ForeignKeys0.FK_PROVIDEREXCLUSION_PROVIDER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.ProviderExclusionRecord, com.incomb.server.model.records.CategoryRecord> FK_PROVIDEREXCLUSION_CATEGORY1 = ForeignKeys0.FK_PROVIDEREXCLUSION_CATEGORY1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.RoleNmPermissionRecord, com.incomb.server.model.records.RoleRecord> FK_ROLE_HAS_PERMISSION_ROLE1 = ForeignKeys0.FK_ROLE_HAS_PERMISSION_ROLE1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.RoleNmPermissionRecord, com.incomb.server.model.records.PermissionRecord> FK_ROLE_HAS_PERMISSION_PERMISSION1 = ForeignKeys0.FK_ROLE_HAS_PERMISSION_PERMISSION1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.RssFeedContentSourceRecord, com.incomb.server.model.records.ContentSourceRecord> FK_RSSFEEDCONTENTSOURCE_CONTENTSOURCE1 = ForeignKeys0.FK_RSSFEEDCONTENTSOURCE_CONTENTSOURCE1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.TagPreferenceRecord, com.incomb.server.model.records.UserRecord> FK_TAGPREFERENCE_USER1 = ForeignKeys0.FK_TAGPREFERENCE_USER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.UserLocaleRecord, com.incomb.server.model.records.UserRecord> FK_USER_LOCALE_USER1 = ForeignKeys0.FK_USER_LOCALE_USER1;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.UserNmRoleRecord, com.incomb.server.model.records.UserRecord> FK_USER_HAS_ROLE_USER = ForeignKeys0.FK_USER_HAS_ROLE_USER;
	public static final org.jooq.ForeignKey<com.incomb.server.model.records.UserNmRoleRecord, com.incomb.server.model.records.RoleRecord> FK_USER_HAS_ROLE_ROLE1 = ForeignKeys0.FK_USER_HAS_ROLE_ROLE1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.incomb.server.model.records.ContentRecord, java.lang.Long> IDENTITY_CONTENT = createIdentity(com.incomb.server.model.tables.ContentTable.CONTENT, com.incomb.server.model.tables.ContentTable.CONTENT.ID);
		public static org.jooq.Identity<com.incomb.server.model.records.ContentCommentRecord, java.lang.Long> IDENTITY_CONTENT_COMMENT = createIdentity(com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT, com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT.ID);
		public static org.jooq.Identity<com.incomb.server.model.records.UserRecord, java.lang.Long> IDENTITY_USER = createIdentity(com.incomb.server.model.tables.UserTable.USER, com.incomb.server.model.tables.UserTable.USER.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.CategoryRecord> KEY_CATEGORY_PRIMARY = createUniqueKey(com.incomb.server.model.tables.CategoryTable.CATEGORY, com.incomb.server.model.tables.CategoryTable.CATEGORY.ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.CategoryPreferenceRecord> KEY_CATEGORY_PREFERENCE_PRIMARY = createUniqueKey(com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE, com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE.USER_ID, com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE.CATEGORY_ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.CombItemRecord> KEY_COMB_ITEM_PRIMARY = createUniqueKey(com.incomb.server.model.tables.CombItemTable.COMB_ITEM, com.incomb.server.model.tables.CombItemTable.COMB_ITEM.USER_ID, com.incomb.server.model.tables.CombItemTable.COMB_ITEM.CONTENT_ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.ContentRecord> KEY_CONTENT_PRIMARY = createUniqueKey(com.incomb.server.model.tables.ContentTable.CONTENT, com.incomb.server.model.tables.ContentTable.CONTENT.ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.ContentCommentRecord> KEY_CONTENT_COMMENT_PRIMARY = createUniqueKey(com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT, com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT.ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.ContentSourceRecord> KEY_CONTENT_SOURCE_PRIMARY = createUniqueKey(com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE, com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.ContentVoteRecord> KEY_CONTENT_VOTE_PRIMARY = createUniqueKey(com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE, com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.USER_ID, com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.CONTENT_ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.FetchHistoryRecord> KEY_FETCH_HISTORY_PRIMARY = createUniqueKey(com.incomb.server.model.tables.FetchHistoryTable.FETCH_HISTORY, com.incomb.server.model.tables.FetchHistoryTable.FETCH_HISTORY.CONTENT_SOURCE_ID, com.incomb.server.model.tables.FetchHistoryTable.FETCH_HISTORY.FETCH_TIME);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.FlyWithRecord> KEY_FLY_WITH_PRIMARY = createUniqueKey(com.incomb.server.model.tables.FlyWithTable.FLY_WITH, com.incomb.server.model.tables.FlyWithTable.FLY_WITH.USER_ID, com.incomb.server.model.tables.FlyWithTable.FLY_WITH.FLY_WITH_ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.ModuleRecord> KEY_MODULE_PRIMARY = createUniqueKey(com.incomb.server.model.tables.ModuleTable.MODULE, com.incomb.server.model.tables.ModuleTable.MODULE.ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.NewsRecord> KEY_NEWS_PRIMARY = createUniqueKey(com.incomb.server.model.tables.NewsTable.NEWS, com.incomb.server.model.tables.NewsTable.NEWS.CONTENT_ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.PermissionRecord> KEY_PERMISSION_PRIMARY = createUniqueKey(com.incomb.server.model.tables.PermissionTable.PERMISSION, com.incomb.server.model.tables.PermissionTable.PERMISSION.ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.ProviderRecord> KEY_PROVIDER_PRIMARY = createUniqueKey(com.incomb.server.model.tables.ProviderTable.PROVIDER, com.incomb.server.model.tables.ProviderTable.PROVIDER.ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.ProviderExclusionRecord> KEY_PROVIDER_EXCLUSION_PRIMARY = createUniqueKey(com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION, com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION.USER_ID, com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION.PROVIDER_ID, com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION.CATEGORY_ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.RoleRecord> KEY_ROLE_PRIMARY = createUniqueKey(com.incomb.server.model.tables.RoleTable.ROLE, com.incomb.server.model.tables.RoleTable.ROLE.ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.RoleNmPermissionRecord> KEY_ROLE_NM_PERMISSION_PRIMARY = createUniqueKey(com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION, com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION.ROLE_ID, com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION.PERMISSION_ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.RssFeedContentSourceRecord> KEY_RSS_FEED_CONTENT_SOURCE_PRIMARY = createUniqueKey(com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE, com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE.CONTENT_SOURCE_ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.TagPreferenceRecord> KEY_TAG_PREFERENCE_PRIMARY = createUniqueKey(com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE, com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE.USER_ID, com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE.TAG);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.UserRecord> KEY_USER_PRIMARY = createUniqueKey(com.incomb.server.model.tables.UserTable.USER, com.incomb.server.model.tables.UserTable.USER.ID);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.UserRecord> KEY_USER_USERNAME_UNIQUE = createUniqueKey(com.incomb.server.model.tables.UserTable.USER, com.incomb.server.model.tables.UserTable.USER.USERNAME);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.UserLocaleRecord> KEY_USER_LOCALE_PRIMARY = createUniqueKey(com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE, com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE.USER_ID, com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE.LOCALE);
		public static final org.jooq.UniqueKey<com.incomb.server.model.records.UserNmRoleRecord> KEY_USER_NM_ROLE_PRIMARY = createUniqueKey(com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE, com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE.USER_ID, com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE.ROLE_ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.CategoryRecord, com.incomb.server.model.records.ModuleRecord> FK_CATEGORY_MODULE1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_MODULE_PRIMARY, com.incomb.server.model.tables.CategoryTable.CATEGORY, com.incomb.server.model.tables.CategoryTable.CATEGORY.MODULE_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.CategoryPreferenceRecord, com.incomb.server.model.records.UserRecord> FK_CATEGORYPREFERENCE_USER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_USER_PRIMARY, com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE, com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE.USER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.CategoryPreferenceRecord, com.incomb.server.model.records.CategoryRecord> FK_CATEGORYPREFERENCE_CATEGORY1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_CATEGORY_PRIMARY, com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE, com.incomb.server.model.tables.CategoryPreferenceTable.CATEGORY_PREFERENCE.CATEGORY_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.CombItemRecord, com.incomb.server.model.records.UserRecord> FK_USER_HAS_CONTENT_USER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_USER_PRIMARY, com.incomb.server.model.tables.CombItemTable.COMB_ITEM, com.incomb.server.model.tables.CombItemTable.COMB_ITEM.USER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.CombItemRecord, com.incomb.server.model.records.ContentRecord> FK_USER_HAS_CONTENT_CONTENT1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_CONTENT_PRIMARY, com.incomb.server.model.tables.CombItemTable.COMB_ITEM, com.incomb.server.model.tables.CombItemTable.COMB_ITEM.CONTENT_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentRecord, com.incomb.server.model.records.ProviderRecord> FK_CONTENT_PROVIDER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_PROVIDER_PRIMARY, com.incomb.server.model.tables.ContentTable.CONTENT, com.incomb.server.model.tables.ContentTable.CONTENT.PROVIDER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentRecord, com.incomb.server.model.records.CategoryRecord> FK_CONTENT_CATEGORY1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_CATEGORY_PRIMARY, com.incomb.server.model.tables.ContentTable.CONTENT, com.incomb.server.model.tables.ContentTable.CONTENT.CATEGORY_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentCommentRecord, com.incomb.server.model.records.UserRecord> FK_CONTENTCOMMENT_USER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_USER_PRIMARY, com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT, com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT.USER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentCommentRecord, com.incomb.server.model.records.ContentRecord> FK_CONTENTCOMMENT_CONTENT1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_CONTENT_PRIMARY, com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT, com.incomb.server.model.tables.ContentCommentTable.CONTENT_COMMENT.CONTENT_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentSourceRecord, com.incomb.server.model.records.ProviderRecord> FK_CONTENTSOURCE_PROVIDER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_PROVIDER_PRIMARY, com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE, com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.PROVIDER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentSourceRecord, com.incomb.server.model.records.CategoryRecord> FK_CONTENTSOURCE_CATEGORY1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_CATEGORY_PRIMARY, com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE, com.incomb.server.model.tables.ContentSourceTable.CONTENT_SOURCE.CATEGORY_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentVoteRecord, com.incomb.server.model.records.UserRecord> FK_CONTENTVOTE_USER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_USER_PRIMARY, com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE, com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.USER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ContentVoteRecord, com.incomb.server.model.records.ContentRecord> FK_CONTENTVOTE_CONTENT1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_CONTENT_PRIMARY, com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE, com.incomb.server.model.tables.ContentVoteTable.CONTENT_VOTE.CONTENT_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.FetchHistoryRecord, com.incomb.server.model.records.ContentSourceRecord> FK_FETCHHISTORY_CONTENTSOURCE1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_CONTENT_SOURCE_PRIMARY, com.incomb.server.model.tables.FetchHistoryTable.FETCH_HISTORY, com.incomb.server.model.tables.FetchHistoryTable.FETCH_HISTORY.CONTENT_SOURCE_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.FlyWithRecord, com.incomb.server.model.records.UserRecord> FK_USER_HAS_USER_USER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_USER_PRIMARY, com.incomb.server.model.tables.FlyWithTable.FLY_WITH, com.incomb.server.model.tables.FlyWithTable.FLY_WITH.USER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.FlyWithRecord, com.incomb.server.model.records.UserRecord> FK_USER_HAS_USER_USER2 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_USER_PRIMARY, com.incomb.server.model.tables.FlyWithTable.FLY_WITH, com.incomb.server.model.tables.FlyWithTable.FLY_WITH.FLY_WITH_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.NewsRecord, com.incomb.server.model.records.ContentRecord> FK_NEWS_CONTENT1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_CONTENT_PRIMARY, com.incomb.server.model.tables.NewsTable.NEWS, com.incomb.server.model.tables.NewsTable.NEWS.CONTENT_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ProviderExclusionRecord, com.incomb.server.model.records.UserRecord> FK_PROVIDEREXCLUSION_USER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_USER_PRIMARY, com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION, com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION.USER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ProviderExclusionRecord, com.incomb.server.model.records.ProviderRecord> FK_PROVIDEREXCLUSION_PROVIDER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_PROVIDER_PRIMARY, com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION, com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION.PROVIDER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.ProviderExclusionRecord, com.incomb.server.model.records.CategoryRecord> FK_PROVIDEREXCLUSION_CATEGORY1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_CATEGORY_PRIMARY, com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION, com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION.CATEGORY_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.RoleNmPermissionRecord, com.incomb.server.model.records.RoleRecord> FK_ROLE_HAS_PERMISSION_ROLE1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_ROLE_PRIMARY, com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION, com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION.ROLE_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.RoleNmPermissionRecord, com.incomb.server.model.records.PermissionRecord> FK_ROLE_HAS_PERMISSION_PERMISSION1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_PERMISSION_PRIMARY, com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION, com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION.PERMISSION_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.RssFeedContentSourceRecord, com.incomb.server.model.records.ContentSourceRecord> FK_RSSFEEDCONTENTSOURCE_CONTENTSOURCE1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_CONTENT_SOURCE_PRIMARY, com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE, com.incomb.server.model.tables.RssFeedContentSourceTable.RSS_FEED_CONTENT_SOURCE.CONTENT_SOURCE_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.TagPreferenceRecord, com.incomb.server.model.records.UserRecord> FK_TAGPREFERENCE_USER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_USER_PRIMARY, com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE, com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE.USER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.UserLocaleRecord, com.incomb.server.model.records.UserRecord> FK_USER_LOCALE_USER1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_USER_PRIMARY, com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE, com.incomb.server.model.tables.UserLocaleTable.USER_LOCALE.USER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.UserNmRoleRecord, com.incomb.server.model.records.UserRecord> FK_USER_HAS_ROLE_USER = createForeignKey(com.incomb.server.model.tables.Keys.KEY_USER_PRIMARY, com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE, com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE.USER_ID);
		public static final org.jooq.ForeignKey<com.incomb.server.model.records.UserNmRoleRecord, com.incomb.server.model.records.RoleRecord> FK_USER_HAS_ROLE_ROLE1 = createForeignKey(com.incomb.server.model.tables.Keys.KEY_ROLE_PRIMARY, com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE, com.incomb.server.model.tables.UserNmRoleTable.USER_NM_ROLE.ROLE_ID);
	}
}
