/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.ModuleRecord> {

	private static final long serialVersionUID = -598314552;

	/**
	 * The reference instance of <code>incomb.module</code>
	 */
	public static final com.incomb.server.model.tables.ModuleTable MODULE = new com.incomb.server.model.tables.ModuleTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.ModuleRecord> getRecordType() {
		return com.incomb.server.model.records.ModuleRecord.class;
	}

	/**
	 * The column <code>incomb.module.id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ModuleRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.module.name_key</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ModuleRecord, java.lang.String> NAME_KEY = createField("name_key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>incomb.module.image_path</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ModuleRecord, java.lang.String> IMAGE_PATH = createField("image_path", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>incomb.module.template_path</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ModuleRecord, java.lang.String> TEMPLATE_PATH = createField("template_path", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * Create a <code>incomb.module</code> table reference
	 */
	public ModuleTable() {
		this("module", null);
	}

	/**
	 * Create an aliased <code>incomb.module</code> table reference
	 */
	public ModuleTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.ModuleTable.MODULE);
	}

	private ModuleTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ModuleRecord> aliased) {
		this(alias, aliased, null);
	}

	private ModuleTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ModuleRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.ModuleRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_MODULE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.ModuleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.ModuleRecord>>asList(com.incomb.server.model.tables.Keys.KEY_MODULE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.ModuleTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.ModuleTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.ModuleTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.ModuleTable(name, null);
	}
}
