/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.NewsRecord> {

	private static final long serialVersionUID = 1384363229;

	/**
	 * The reference instance of <code>incomb.news</code>
	 */
	public static final com.incomb.server.model.tables.NewsTable NEWS = new com.incomb.server.model.tables.NewsTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.NewsRecord> getRecordType() {
		return com.incomb.server.model.records.NewsRecord.class;
	}

	/**
	 * The column <code>incomb.news.content_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.NewsRecord, java.lang.Long> CONTENT_ID = createField("content_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.news.link</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.NewsRecord, java.lang.String> LINK = createField("link", org.jooq.impl.SQLDataType.CLOB.length(16777215).nullable(false), this, "");

	/**
	 * The column <code>incomb.news.image_url</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.NewsRecord, java.lang.String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.CLOB.length(16777215), this, "");

	/**
	 * The column <code>incomb.news.image_width</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.NewsRecord, java.lang.Integer> IMAGE_WIDTH = createField("image_width", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>incomb.news.image_height</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.NewsRecord, java.lang.Integer> IMAGE_HEIGHT = createField("image_height", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>incomb.news.news_group_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.NewsRecord, java.lang.Long> NEWS_GROUP_ID = createField("news_group_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>incomb.news</code> table reference
	 */
	public NewsTable() {
		this("news", null);
	}

	/**
	 * Create an aliased <code>incomb.news</code> table reference
	 */
	public NewsTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.NewsTable.NEWS);
	}

	private NewsTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.NewsRecord> aliased) {
		this(alias, aliased, null);
	}

	private NewsTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.NewsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.NewsRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_NEWS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.NewsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.NewsRecord>>asList(com.incomb.server.model.tables.Keys.KEY_NEWS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.NewsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.NewsRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_NEWS_CONTENT1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.NewsTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.NewsTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.NewsTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.NewsTable(name, null);
	}
}
