/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.PermissionRecord> {

	private static final long serialVersionUID = -1465517495;

	/**
	 * The reference instance of <code>incomb.permission</code>
	 */
	public static final com.incomb.server.model.tables.PermissionTable PERMISSION = new com.incomb.server.model.tables.PermissionTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.PermissionRecord> getRecordType() {
		return com.incomb.server.model.records.PermissionRecord.class;
	}

	/**
	 * The column <code>incomb.permission.id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.PermissionRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.permission.name_key</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.PermissionRecord, java.lang.String> NAME_KEY = createField("name_key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>incomb.permission</code> table reference
	 */
	public PermissionTable() {
		this("permission", null);
	}

	/**
	 * Create an aliased <code>incomb.permission</code> table reference
	 */
	public PermissionTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.PermissionTable.PERMISSION);
	}

	private PermissionTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.PermissionRecord> aliased) {
		this(alias, aliased, null);
	}

	private PermissionTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.PermissionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.PermissionRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_PERMISSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.PermissionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.PermissionRecord>>asList(com.incomb.server.model.tables.Keys.KEY_PERMISSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.PermissionTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.PermissionTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.PermissionTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.PermissionTable(name, null);
	}
}
