/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProviderExclusionTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.ProviderExclusionRecord> {

	private static final long serialVersionUID = 1159384176;

	/**
	 * The reference instance of <code>incomb.provider_exclusion</code>
	 */
	public static final com.incomb.server.model.tables.ProviderExclusionTable PROVIDER_EXCLUSION = new com.incomb.server.model.tables.ProviderExclusionTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.ProviderExclusionRecord> getRecordType() {
		return com.incomb.server.model.records.ProviderExclusionRecord.class;
	}

	/**
	 * The column <code>incomb.provider_exclusion.user_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ProviderExclusionRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.provider_exclusion.provider_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ProviderExclusionRecord, java.lang.Integer> PROVIDER_ID = createField("provider_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.provider_exclusion.category_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ProviderExclusionRecord, java.lang.Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>incomb.provider_exclusion</code> table reference
	 */
	public ProviderExclusionTable() {
		this("provider_exclusion", null);
	}

	/**
	 * Create an aliased <code>incomb.provider_exclusion</code> table reference
	 */
	public ProviderExclusionTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.ProviderExclusionTable.PROVIDER_EXCLUSION);
	}

	private ProviderExclusionTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ProviderExclusionRecord> aliased) {
		this(alias, aliased, null);
	}

	private ProviderExclusionTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ProviderExclusionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.ProviderExclusionRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_PROVIDER_EXCLUSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.ProviderExclusionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.ProviderExclusionRecord>>asList(com.incomb.server.model.tables.Keys.KEY_PROVIDER_EXCLUSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.ProviderExclusionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.ProviderExclusionRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_PROVIDEREXCLUSION_USER1, com.incomb.server.model.tables.Keys.FK_PROVIDEREXCLUSION_PROVIDER1, com.incomb.server.model.tables.Keys.FK_PROVIDEREXCLUSION_CATEGORY1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.ProviderExclusionTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.ProviderExclusionTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.ProviderExclusionTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.ProviderExclusionTable(name, null);
	}
}
