/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProviderTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.ProviderRecord> {

	private static final long serialVersionUID = 341975048;

	/**
	 * The reference instance of <code>incomb.provider</code>
	 */
	public static final com.incomb.server.model.tables.ProviderTable PROVIDER = new com.incomb.server.model.tables.ProviderTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.ProviderRecord> getRecordType() {
		return com.incomb.server.model.records.ProviderRecord.class;
	}

	/**
	 * The column <code>incomb.provider.id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ProviderRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.provider.name</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ProviderRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>incomb.provider.image_path</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ProviderRecord, java.lang.String> IMAGE_PATH = createField("image_path", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>incomb.provider.website</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ProviderRecord, java.lang.String> WEBSITE = createField("website", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>incomb.provider.parser_class</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.ProviderRecord, java.lang.String> PARSER_CLASS = createField("parser_class", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>incomb.provider</code> table reference
	 */
	public ProviderTable() {
		this("provider", null);
	}

	/**
	 * Create an aliased <code>incomb.provider</code> table reference
	 */
	public ProviderTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.ProviderTable.PROVIDER);
	}

	private ProviderTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ProviderRecord> aliased) {
		this(alias, aliased, null);
	}

	private ProviderTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.ProviderRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.ProviderRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_PROVIDER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.ProviderRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.ProviderRecord>>asList(com.incomb.server.model.tables.Keys.KEY_PROVIDER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.ProviderTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.ProviderTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.ProviderTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.ProviderTable(name, null);
	}
}
