/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleNmPermissionTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.RoleNmPermissionRecord> {

	private static final long serialVersionUID = 497441523;

	/**
	 * The reference instance of <code>incomb.role_nm_permission</code>
	 */
	public static final com.incomb.server.model.tables.RoleNmPermissionTable ROLE_NM_PERMISSION = new com.incomb.server.model.tables.RoleNmPermissionTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.RoleNmPermissionRecord> getRecordType() {
		return com.incomb.server.model.records.RoleNmPermissionRecord.class;
	}

	/**
	 * The column <code>incomb.role_nm_permission.role_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.RoleNmPermissionRecord, java.lang.Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>incomb.role_nm_permission.permission_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.RoleNmPermissionRecord, java.lang.Integer> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>incomb.role_nm_permission</code> table reference
	 */
	public RoleNmPermissionTable() {
		this("role_nm_permission", null);
	}

	/**
	 * Create an aliased <code>incomb.role_nm_permission</code> table reference
	 */
	public RoleNmPermissionTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.RoleNmPermissionTable.ROLE_NM_PERMISSION);
	}

	private RoleNmPermissionTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.RoleNmPermissionRecord> aliased) {
		this(alias, aliased, null);
	}

	private RoleNmPermissionTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.RoleNmPermissionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.RoleNmPermissionRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_ROLE_NM_PERMISSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.RoleNmPermissionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.RoleNmPermissionRecord>>asList(com.incomb.server.model.tables.Keys.KEY_ROLE_NM_PERMISSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.RoleNmPermissionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.RoleNmPermissionRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_ROLE_HAS_PERMISSION_ROLE1, com.incomb.server.model.tables.Keys.FK_ROLE_HAS_PERMISSION_PERMISSION1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.RoleNmPermissionTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.RoleNmPermissionTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.RoleNmPermissionTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.RoleNmPermissionTable(name, null);
	}
}
