/**
 * This class is generated by jOOQ
 */
package com.incomb.server.model.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagPreferenceTable extends org.jooq.impl.TableImpl<com.incomb.server.model.records.TagPreferenceRecord> {

	private static final long serialVersionUID = -302089974;

	/**
	 * The reference instance of <code>incomb.tag_preference</code>
	 */
	public static final com.incomb.server.model.tables.TagPreferenceTable TAG_PREFERENCE = new com.incomb.server.model.tables.TagPreferenceTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.incomb.server.model.records.TagPreferenceRecord> getRecordType() {
		return com.incomb.server.model.records.TagPreferenceRecord.class;
	}

	/**
	 * The column <code>incomb.tag_preference.user_id</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.TagPreferenceRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>incomb.tag_preference.tag</code>.
	 */
	public final org.jooq.TableField<com.incomb.server.model.records.TagPreferenceRecord, java.lang.String> TAG = createField("tag", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>incomb.tag_preference</code> table reference
	 */
	public TagPreferenceTable() {
		this("tag_preference", null);
	}

	/**
	 * Create an aliased <code>incomb.tag_preference</code> table reference
	 */
	public TagPreferenceTable(java.lang.String alias) {
		this(alias, com.incomb.server.model.tables.TagPreferenceTable.TAG_PREFERENCE);
	}

	private TagPreferenceTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.TagPreferenceRecord> aliased) {
		this(alias, aliased, null);
	}

	private TagPreferenceTable(java.lang.String alias, org.jooq.Table<com.incomb.server.model.records.TagPreferenceRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.incomb.server.model.tables.IncombTable.INCOMB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.incomb.server.model.records.TagPreferenceRecord> getPrimaryKey() {
		return com.incomb.server.model.tables.Keys.KEY_TAG_PREFERENCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.incomb.server.model.records.TagPreferenceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.incomb.server.model.records.TagPreferenceRecord>>asList(com.incomb.server.model.tables.Keys.KEY_TAG_PREFERENCE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.incomb.server.model.records.TagPreferenceRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.incomb.server.model.records.TagPreferenceRecord, ?>>asList(com.incomb.server.model.tables.Keys.FK_TAGPREFERENCE_USER1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.incomb.server.model.tables.TagPreferenceTable as(java.lang.String alias) {
		return new com.incomb.server.model.tables.TagPreferenceTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.incomb.server.model.tables.TagPreferenceTable rename(java.lang.String name) {
		return new com.incomb.server.model.tables.TagPreferenceTable(name, null);
	}
}
